# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  pull_request:
  schedule:
    - cron: '0 18 * * *'  # TimeZone: UTC 0

concurrency:
  group: ci-it-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  license:
    name: Check License
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check License Header
        uses: apache/skywalking-eyes@9bd5feb86b5817aa6072b008f9866a2c3bbc8587
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Java ${{ matrix.java-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 60
    needs: [ license ]
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu, macos, windows ]
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-ci-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-ci-
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Check Javaagent Plugin List
        run: tools/plugin/check-javaagent-plugin-list.sh
      - name: Install and Test
        run: ./mvnw -q --batch-mode clean verify install javadoc:javadoc

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - run: echo 'Success'
