# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: E2E

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  schedule:
    - cron: '0 18 * * *'

env:
  SKIP_TEST: true
  SW_AGENT_JDK_VERSION: 8
  CODECOV_TOKEN: d2065307-8f01-4637-9715-2781ef096db7

jobs:
  Profiling:
    name: Profiling
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        storage: ['h2', 'mysql', 'es6', 'es7', 'influxdb']
    env:
      SW_STORAGE: ${{ matrix.storage }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile and Build
        run: make docker && ES_VERSION=es7 TAG=latest-es7 make docker.oap
      - name: Copy dist package
        run: cp -R dist test/e2e/
      - name: Profiling ${{ matrix.storage }}
        run: ./mvnw --batch-mode -f test/e2e/pom.xml -am -DfailIfNoTests=false verify -Dit.test=org.apache.skywalking.e2e.profile.ProfileE2E
      - name: Report Coverage
        run: bash -x tools/coverage/report.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
